services:
  - type: web
    name: daatsin-tsamkhag-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://daatsin-tsamkhag-backend.onrender.com
      - key: PORT
        value: 10000
